name: subtask 1

# Manually trigger the workflow.
on: workflow_dispatch

jobs:
  run:
    name: run
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: install
        run: python -m pip install -r requirements.txt
      - name: run
        run: python -m src.subtask1
      - name: commit
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'tslwn@users.noreply.github.com'
          git add results
          git commit -m "[results] `date +"%FT%TZ"`"
          git push
